### ISSUE TITLE
thunderbolt display

### ISSUE THREAD

**Issue by MasseGuillaume** [puffnfresh/nix-files#1]
I canot connect to an external monitor. Any pointers on what could be the issue ?

**Comment by puffnfresh** [comment]
Linux kernel 3.17 got some Thunderbolt support but did not gain enough support to drive a display.

**Comment by MasseGuillaume** [comment]
Works on 3.18

**Comment by puffnfresh** [comment]
I tried but couldn't boot with 3.18 :crying_cat_face:

Great to hear that it works though :fireworks:

**Comment by melissanoelle** [comment]
@MasseGuillaume can you link me to any where with more information on whether a Thunderbolt external monitor will work?

**Comment by malakada** [comment]
@MasseGuillaume do you have Thunderbolt external monitors working here: https://github.com/MasseGuillaume/nix-files ? I tried to find a way to open a discussion issue there, but it seems that issues are turned off for the repo.

**Comment by MasseGuillaume** [comment]
@melissanoelle I got fired at my prev job and I got to give my laptop back. Note that the current repo now reflects my personal computer and I forced push on master so the history is gone :-(.

Based on what I remember:
set https://github.com/puffnfresh/nix-files/blob/master/configuration.nix#L33 to `pkgs.linuxPackages_3_18`
remove https://github.com/puffnfresh/nix-files/blob/master/configuration.nix#L123
set https://github.com/puffnfresh/nix-files/blob/master/configuration.nix#L141

```
linux_3_18 = pkgs.linux_3_18.override {
        extraConfig =
        ''
          THUNDERBOLT m
        '';
```

kernel 3.18.17 is currently the latest longtime kernel https://www.kernel.org/. When I tried kernel 4._._ was not working

If we take a look at the various [change log](https://www.google.ca/search?sourceid=chrome-psyapi2&ion=1&espv=2&ie=UTF-8&q=site%3Ahttps%3A%2F%2Fwww.kernel.org%2Fpub%2Flinux%2Fkernel%2F%20thunderbolt&oq=site%3Ahttps%3A%2F%2Fwww.kernel.org%2Fpub%2Flinux%2Fkernel%2F%20thunderbolt&aqs=chrome..69i57j69i58.8366j0j4) there is nothing really relevant to thunderbolt from 3.17._ to 3.18._. Maybe the screenSection is relevant ?

I had an external apple monitor with thunderbolt. It was connected to an ethernet cable and both the video and the Ethernet was working. I had a hard time struggling with the retina display. The current solution is this repo is to scale the resolution. But it does not look great. Sorry for being really vague.

**Comment by malakada** [comment]
This is still pretty helpful, thanks! I'll definitely be referencing this this week. When you say you had trouble with the retina display, did you mean the actual retina display of the laptop, or an external retina monitor?

**Comment by MasseGuillaume** [comment]
The laptop display. You have to compile programs for HiDPI support. For example: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/chromium/default.nix#L16
