### ISSUE TITLE
[question] Managing user environment

### ISSUE THREAD

**Issue by bobymicroby** [puffnfresh/nix-files#2]
Hey Brian, 

Which approach are you using for managing your user environment? Do you just ```nix-env -f user.nix - i``` , or you somehow hook it to the configuration.nix / profiles / home-manager so you can switch ?

Basically I want to be able to switch generations based on the revision of user.nix in git  .

**Comment by puffnfresh** [comment]
Yes, I use nix-env. Each time you use nix-env it creates a generation, so you can rollback. Take a look at these two commands:

* `nix-env --list-generations`
* `nix-env --switch-generation {generation}`

**Comment by bobymicroby** [comment]
Awesome ! I was too sloppy with the nix manual :man_facepalming:  Thanks for the tip and the nix files, they are so neat-o ;)
